export const SUCCESS = "SUCCESS"

export const FAILURE = "FAILURE"

export const LOGIN_SUCCESS = "LOGIN_SUCCESS"

export const LOGIN_FAILURE = "LOGIN_FAILURE"

export const ADD_PROFILE = "ADD_PROFILE"

export const REMOVE_PROFILE = "REMOVE_PROFILE"

export const USER_INPUT_CHANGE = "USER_INPUT_CHANGE"

export const USER_INPUT_SUBMIT = "USER_INPUT_SUBMIT"

export const FETCH_CAMERAS_FAILURE = "FETCH_CAMERAS_FAILURE"

export const FETCH_CAMERAS_SUCCESS = "FETCH_CAMERAS_SUCCESS"

export const SET_CURRENT_CAMERA = "SET_CURRENT_CAMERA"

export const FETCH_VEHICLES_SUCCESS = "FETCH_VEHICLES_SUCCESS"

export const SET_CURRENT_VEHICLE = "SET_CURRENT_VEHICLE"

export const FETCH_PHONE_NUMBERS = "FETCH_PHONE_NUMBERS"